Repository platiniromina/be_java_hisp_w31_g07, pull requests merged in 2025-05, with the labels that each got.

#81 T0009: Unit test for createPromoPost (US10)
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/dto/request/PostDto.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/BuyerService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/ProductService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/SellerService.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/PostFactory.java
Labels: unit

#80 T0028 - Add Integration Tests for Get Post
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IPostRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/ISellerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/PostRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/SellerRepository.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/JsonUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/PostFactory.java
Labels: integration, urgente

#87 Refactor Mayor - Requiere atención urgente
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/IBuyerController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/IFollowController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/IProductController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/implementations/BuyerController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/implementations/FollowController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/implementations/ProductController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/exception/GlobalExceptionHandler.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IBuyerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IProductRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/ISellerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IUserRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/SellerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/UserRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IBuyerService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IFollowService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IPostBridgeService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IPostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IProductService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/ISellerService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IUserService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/BuyerService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/FollowService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostBridgeService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/ProductService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/SellerService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/UserService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/BuyerMapper.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ErrorMessagesUtil.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/GenericObjectMapper.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/IdUtils.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/PostMapper.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/SortUtil.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/UserUtil.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ValidationUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/BuyerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/FollowerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/SellerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/UserServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/BuyerFactory.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/SellerFactory.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/UserFactory.java
Labels: urgente

#84 T0010: Unit test for getPromoPostsCount (US11)
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
Labels: unit, compatible

#86 T0025: Integration test for getUserPromoPostCount (US11)
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IUserRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/UserRepository.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
Labels: integration, compatible

#79 T0003 y T0004: Unit test for SortedFollowersByName (US08)
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/BuyerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/FollowerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/SellerServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/BuyerFactory.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/SellerFactory.java
Labels: unit, compatible

#82 T0024 & T0035: Integration test for createPost & createPromoPost (US05 y US10)
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/dto/request/PostDto.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/dto/request/ProductDto.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/exception/GlobalExceptionHandler.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IPostRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/PostRepository.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/JsonUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/PostFactory.java
Labels: integration, compatible

#92 T0011 - Get promo post list for a Seller
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ErrorMessagesUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/UserFactory.java
Labels: unit, compatible

#89 Test/t0023 integration get latest posts
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/IBuyerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/repository/implementations/BuyerRepository.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ErrorMessagesUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
Labels: integration

#93 T0012 - Get Average Promo Post By User
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ErrorMessagesUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
Labels: unit

#94 T0026 - Integration test Get promotion posts by seller.
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/util/ErrorMessagesUtil.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
Labels: integration

#95 T0027 - Integration test - Get average post by user
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/IProductController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/controller/implementations/ProductController.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/dto/response/SellerAveragePriceDto.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/IPostService.java
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/service/implementations/PostService.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/ProductControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
Labels: integration

#97 T0033 - Get followers list
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/FollowControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/BuyerFactory.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/SellerFactory.java
Labels: integration

#99 T0034 - Get followed list
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/controller/FollowControllerTest.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/BuyerFactory.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/util/SellerFactory.java
Labels: integration

#91 Unit t0005 verify sortedposts bydate
  src/main/java/com/mercadolibre/be_java_hisp_w31_g07/model/Buyer.java
  src/test/java/com/mercadolibre/be_java_hisp_w31_g07/service/PostServiceTest.java
Labels: unit
